image: Ubuntu  # образ для сборки

stack: jdk 11

branches:
  only:
    - main  # ветка git

build: off  # будем использовать свой скрипт сборки

install:
  - java -jar ./artifacts/app-ibank.jar -P:profile=test &

build_script:
  - chmod +x gradlew
  - ./gradlew test -Dselenide.headless=true --info